spring:
  main:
    web-environment: true
    show-banner: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23141/seiso?autoReconnect=true
    username: seiso
    password: seiso
    # TODO Add other data source settings here
  jpa:
    openInView: true
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  rabbitmq:
    host: 127.0.0.1
    port: 23142
    username: seiso
    password: seiso

logging:
#  file: /var/log/seiso/seiso.log
  level:
    com.expedia.seiso: TRACE
    com.expedia.serf: TRACE
    org.springframework: INFO

security:
  basic:
    enabled: false

# IMPORTANT: This is a potential security risk, so use discretion.
# The admin panel currently assumes that endpoints.health.sensitive is false.
endpoints:
  health:
    sensitive: false

serf:
  # No trailing slash!
  base-uri: http://localhost:8080
  base-path: api

custom:
  change-notification-exchange: seiso.notifications.v2
